### PR TITLE
1.1.0 Release

### PR DESCRIPTION
**Pull request by nblumhardt**
* #104 - don't mark canceled ASP.NET Core requests as errors, and attach `RequestAborted: true` to resulting spans when this does occur (@nblumhardt)
 * #103 - make `HttpClient` instrumentation more configurable (@nblumhardt)
 * #106 - make `SqlClient` instrumentation more configurable (@nblumhardt)

### CODE REVIEW

**Comment by brendangooden** [comment]
@nblumhardt  Thanks for the updates! Do you know when `1.1.0` will be released? We are waiting with bated breath for the configurable `HttpClient` instrumentation :)

**Comment by nblumhardt** [comment]
@brendangooden I don't think anything should hold it up, the changes are fairly low risk. It would be great to get some validation around the APIs - are you able to try out the `1.1.0-dev-*` builds locally and let me know that your use case is covered properly?

**Comment by brendangooden** [comment]
@nblumhardt  is there a pre-release nuget available?

**Comment by nblumhardt** [comment]
👍  https://www.nuget.org/packages/SerilogTracing/1.1.0-dev-00287

**Comment by nblumhardt** [comment]
(All of the SerilogTracing.* prerelease packages are published to NuGet.org)

**Comment by brendangooden** [comment]
@nblumhardt  - my apologies, should have checked first. Updating now, will advise any issues

**Comment by brendangooden** [comment]
@nblumhardt  - unless I'm doing something wrong, i've updated to `1.1.0-dev-00287` and its still using the old implementation of `DefaultIsErrorResponse` ? 

image

**Comment by nblumhardt** [comment]
Hi @brendangooden - this is expected, the change was to make it configurable. You need something like:

```csharp
    .Instrument.WithDefaultInstrumentation(false)
    .Instrument.HttpClientRequests(opts => opts.IsErrorResponse = (r) => ((int)r.StatusCode) >= 500)
```

**Comment by brendangooden** [comment]
@nblumhardt 

The commit specifically mentioned not treating an aborted response as an error . Unless I've missed something I can't see this in the pre-release?
 https://github.com/serilog-tracing/serilog-tracing/commit/4cbee26e72d46a73196638d9ceb874dbbc86cf00

**Comment by nblumhardt** [comment]
Hi @brendangooden! That change is in the ASP.NET Core instrumentation, not for `HttpClient`. It'd be awesome if we could do the same thing on the client-side; open to including this on the client, too - I'll take a look :eyes:

**Comment by brendangooden** [comment]
@nblumhardt  - My apologies. Digging into this, there's a difference between the ASP.NET Core instrumentation and the HttpClient instrumentation. I need the new behaviour for HttpClient instrumentation so I'll just modify the options manually as you've indicated.

**Pull request merged**
